version: 2

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - main: .
    binary: notes-mcp
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE*
      - README*
      - docs/*

brews:
  - repository:
      owner: harperreed
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    directory: Formula
    homepage: "https://github.com/harperreed/notes-mcp"
    description: "MCP server for Apple Notes with CLI tools"
    install: |
      bin.install "notes-mcp"
    test: |
      system "#{bin}/notes-mcp", "help"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
