version: 2

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - main: .
    binary: pagen
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=1
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{.Version}}
    overrides:
      - goos: darwin
        goarch: amd64
        env:
          - CGO_ENABLED=1
          - CC=zig cc -target x86_64-macos
      - goos: darwin
        goarch: arm64
        env:
          - CGO_ENABLED=1
          - CC=zig cc -target aarch64-macos
      - goos: linux
        goarch: amd64
        env:
          - CGO_ENABLED=1
          - CC=zig cc -target x86_64-linux-gnu
      - goos: linux
        goarch: arm64
        env:
          - CGO_ENABLED=1
          - CC=zig cc -target aarch64-linux-gnu

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE*
      - README*
      - docs/*

brews:
  - repository:
      owner: harperreed
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    directory: Formula
    homepage: "https://github.com/harperreed/pagen"
    description: "Personal Agent Toolkit - CRM with MCP server and CLI"
    install: |
      bin.install "pagen"
    test: |
      system "#{bin}/pagen", "--version"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
