# ABOUTME: GoReleaser configuration for building and releasing pagen
# ABOUTME: Builds macOS binaries and publishes to Homebrew tap; Linux handled by CI workflow

version: 2

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - main: .
    binary: pagen
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=1
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE*
      - README*
      - docs/*

brews:
  - repository:
      owner: harperreed
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    directory: Formula
    homepage: "https://github.com/harperreed/pagen"
    description: "Personal Agent Toolkit - CRM with MCP server and CLI"
    install: |
      bin.install "pagen"
    test: |
      system "#{bin}/pagen", "--version"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
